language: php
php:
  - 7.0

sudo: false

env:
  global:
    - SIMPLETEST_DB=mysql://root:@localhost/hodges
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

services:
  - mysql

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer --verbose self-update
  - composer --version

install:
  - mysql --execute='CREATE DATABASE hodges;'
  # We require coveralls like this as it won't work straight from composer.json.
  - composer require satooshi/php-coveralls
  - composer --verbose install
  - composer drupal-scaffold

script:
  - cp $TRAVIS_BUILD_DIR/config/travis.settings.php $TRAVIS_BUILD_DIR/config/local.settings.php
  - cd $TRAVIS_BUILD_DIR/web
  - $TRAVIS_BUILD_DIR/vendor/bin/drush site-install config_installer --account-name=admin --account-pass=admin --site-name="Hodges" --yes
  - $TRAVIS_BUILD_DIR/vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p $TRAVIS_BUILD_DIR/build/logs
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c $TRAVIS_BUILD_DIR/phpunit.xml.dist
